### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by ghost** [teracyhq/httpie-jwt-auth#33]
Installation output

```
❯ pip install httpie
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support                                                                                                                                          
Defaulting to user installation because normal site-packages is not writeable
Collecting httpie
  Using cached httpie-2.0.0-py2.py3-none-any.whl (64 kB)
Requirement already satisfied: requests>=2.22.0 in ./.local/lib/python2.7/site-packages (from httpie) (2.22.0)
Requirement already satisfied: Pygments>=2.5.2 in ./.local/lib/python2.7/site-packages (from httpie) (2.5.2)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python2.7/site-packages (from requests>=2.22.0->httpie) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/lib/python2.7/site-packages (from requests>=2.22.0->httpie) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./.local/lib/python2.7/site-packages (from requests>=2.22.0->httpie) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./.local/lib/python2.7/site-packages (from requests>=2.22.0->httpie) (1.25.8)
Installing collected packages: httpie
Successfully installed httpie-2.0.0

❯ pip install httpie-jwt-auth
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting httpie-jwt-auth
  Using cached httpie_jwt_auth-0.3.0-py2.py3-none-any.whl (8.3 kB)
Requirement already satisfied: httpie>=0.9.7 in ./.local/lib/python2.7/site-packages (from httpie-jwt-auth) (2.0.0)
Requirement already satisfied: requests>=2.22.0 in ./.local/lib/python2.7/site-packages (from httpie>=0.9.7->httpie-jwt-auth) (2.22.0)
Requirement already satisfied: Pygments>=2.5.2 in ./.local/lib/python2.7/site-packages (from httpie>=0.9.7->httpie-jwt-auth) (2.5.2)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python2.7/site-packages (from requests>=2.22.0->httpie>=0.9.7->httpie-jwt-auth) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/lib/python2.7/site-packages (from requests>=2.22.0->httpie>=0.9.7->httpie-jwt-auth) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./.local/lib/python2.7/site-packages (from requests>=2.22.0->httpie>=0.9.7->httpie-jwt-auth) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./.local/lib/python2.7/site-packages (from requests>=2.22.0->httpie>=0.9.7->httpie-jwt-auth) (1.25.8)
Installing collected packages: httpie-jwt-auth
Successfully installed httpie-jwt-auth-0.3.0

```

Test

```
❯ http --auth-type=jwt --auth="token" 127.0.0.1:32769
Traceback (most recent call last):
  File "/home/user/.local/bin/http", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python2.7/site-packages/httpie/__main__.py", line 10, in main
    from .core import main
  File "/home/user/.local/lib/python2.7/site-packages/httpie/core.py", line 21
    args: List[Union[str, bytes]] = sys.argv,
        ^
SyntaxError: invalid syntax

```
```

❯ python --version
Python 2.7.17

```

**Comment by ghost** [comment]
If I remove httpie from pip and install it from apt repo I get the error

```
❯ sudo apt install httpie
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libgtkd-3-0 libphobos2-ldc-shared78 libvte-2.91-0 libvte-2.91-common libvted-3-0 tilix-common
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  httpie
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/67.1 kB of archives.
After this operation, 243 kB of additional disk space will be used.
Selecting previously unselected package httpie.
(Reading database ... 324416 files and directories currently installed.)
Preparing to unpack .../httpie_0.9.8-2_all.deb ...
Unpacking httpie (0.9.8-2) ...
Setting up httpie (0.9.8-2) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
```
test

```
❯ http --auth-type=jwt --auth="token" 127.0.0.1:32769
usage: http [--json] [--form] [--pretty {all,colors,format,none}]
            [--style STYLE] [--print WHAT] [--headers] [--body] [--verbose]
            [--all] [--history-print WHAT] [--stream] [--output FILE]
            [--download] [--continue]
            [--session SESSION_NAME_OR_PATH | --session-read-only SESSION_NAME_OR_PATH]
            [--auth USER[:PASS]] [--auth-type {basic,digest}]
            [--proxy PROTOCOL:PROXY_URL] [--follow]
            [--max-redirects MAX_REDIRECTS] [--timeout SECONDS]
            [--check-status] [--verify VERIFY]
            [--ssl {ssl2.3,tls1,tls1.1,tls1.2}] [--cert CERT]
            [--cert-key CERT_KEY] [--ignore-stdin] [--help] [--version]
            [--traceback] [--default-scheme DEFAULT_SCHEME] [--debug]
            [METHOD] URL [REQUEST_ITEM [REQUEST_ITEM ...]]
http: error: argument --auth-type/-A: invalid choice: 'jwt' (choose from 'basic', 'digest')
```

**Comment by frjaraur** [comment]
Same here

**Comment by datphan** [comment]
@unexpectedShr3k Please try python 3.6 as required by `httpie 2.0`
https://httpie.org/doc#python-version

First, try to clean up
```bash
$ rm -rf /usr/local/lib/python2.7/dist-packages/httpie/
$ apt remove httpie
$ pip uninstall httpie 
```

Then
```bash
$ apt install python3-pip
$ pip3 install httpie
$ pip3 install httpie-jwt-auth
$ http --auth-type=jwt --auth="token" github.com -v
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer token
Connection: keep-alive
Host: github.com
User-Agent: HTTPie/2.0.0



HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://github.com/
```

**Comment by ghost** [comment]
@datphan it works. thanks.
